<!DOCTYPE html>
<html>
<head>
  <title>DOM</title>
  <script src="/js/dom.js"></script>
  <link rel="stylesheet" type="text/css" href="/css/base.css">
</head>
<body>
  <h1>DOM Debugging</h1>
  <p>
    Element breakpoints, Element event listeners, CSS psuedo selectors
  </p>

  <button class="insert-node">Clone Node</button>
  <h2>Section 1</h2>
  <p>Some text that will be highlighted on hover.</p>
  <h2>Section 2</h2>
  <p>Some more text that will be highlighted on hover.</p>
</body>
</html>
